# Generated by Django 5.1.6 on 2025-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_task_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=50),
            preserve_default=False,
        ),
    ]
